### PR TITLE
Implementing proto.Clone

### PR DESCRIPTION
**Pull request by im-kulikov**
I propose to discuss this functionality because it is quite convenient and in demand in the code.

### CODE REVIEW

**Comment by cthulhu-rider** [comment]
@im-kulikov, could you please describe what is the intended use of the provided `proto.Merger` interface?

**Comment by im-kulikov** [comment]
For example proto.Clone used proto.Merger interface to make copy of anything. In our case, if you try to make copy of refs.Address, you see “don’t know how to copy xxxx”

**Comment by cthulhu-rider** [comment]
@im-kulikov, got it, it's about the package `gogo/protobuf/proto`, not `golang/protobuf/proto `. Hanx!

**Comment by AlexVanin** [comment]
@im-kulikov Please, change destination branch to `develop`, not `master`.

**Comment by im-kulikov** [comment]
Oh, ok

**Pull request merged**
